version: '3.9'

networks:
  galera_network:
    name: galera_network
    attachable: true
    driver: overlay
    ipam:
      config:
        - subnet: 10.0.10.0/24

services:
  seed: &default_service
    image: colinmollenhour/mariadb-galera-swarm:10.4.32-2023-12-09
    env_file:
      - .env
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
    networks:
      - galera_network
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
    command: seed
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  node:
    <<: *default_service
    command: node tasks.seed,tasks.node
    environment:
      - NODE_ADDRESS=^10.0.*.*
      - HEALTHY_WHILE_BOOTING=1
    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.labels.role == node-{{.Task.Slot}}
    healthcheck: # Отключаем healthcheck для node
      test: []

volumes:
  mysql-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password
